apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: npe5seconds
  name: npe5seconds
spec:
  containers:
  - image: dervilo/npe5seconds
    name: npe5seconds
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
